version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SWIFEY_REDIS_HOST=redis
      - SWIFEY_REDIS_PORT=6379
    volumes:
      - ./models:/app/models
      - ./swifey.db:/app/swifey.db
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
